title: Isa Muhammad Sa'id
subtitle: Personal website for education purpose
description: >- # this means to ignore newlines until "baseurl:"
  isamsaid.com is one of website for everyone who want to learn.

url: "https://id.isamsaid.com" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog
cdn_url: https://cdn.isamsaid.com/isamsai2/id.isamsaid.com # CDN Version

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact
      url : /contact
    - text: Styleguide
      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Isa Muhammad Sa'id
author_bio: Automobile Engineering
author_email: "isamsaid@polinema.ac.id"
author_location: Indonesia
author_website_url: "https://isamsaid.com"
typewrite-text: Welcome to this website, hope you enjoy !

# Experiences
author_work_experiences:
            - company_name: PT Astra International Tbk
              company_logo: astrainternational.png
              company_url: https://www.astra.co.id/
              designation: Other
              description: Worked & Studied for two years
              visibility: true
            - company_name: PT. Altrak 1978
              company_logo: altrak1978.png
              company_url: https://www.altrak1978.co.id/
              designation: Education
              description: Training & Development Department
              visibility: true
            - company_name: State Polytechnic of Malang
              company_logo: polinema.jpeg
              company_url: https://www.polinema.ac.id/
              designation: Education
              description: Lecture
              visibility: true

# Education
author_education_details:
              - college_logo: pascasarjana.png
                college_name: Pascasarjana Universitas Negeri Malang
                college_url: http://pasca.um.ac.id/
                college_degree: Mechanical Engineering (Automotive)
                description: Master of Arts
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: rg.png
                project_title: Researchgate
                project_description: Project for Research Paper
                project_url: https://www.researchgate.net/profile/Isa-Said
                visibility: true
             # - project_thumbnail: hack4r.PNG
             #   project_title: Hack4r
             #   project_description: A Platform built for Hackers and Penetration Testers
             #   project_url: https://hack4r.com
             #   visibility: true

# social links
twitter_username: IsaSaid11
github_username:  isa-7
facebook_username: yokephoebe
linkedin_username: 
behance_username: 
instagram_username: yokeofphoebe
medium_username: 
telegram_username: 
dribbble_username: 
flickr_username: 

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 4061

# wakatime username (coding activity)
wakatime_username: isasaid

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://us1.list-manage.com/survey?u=be9ca4bd7ec38fa4e6a1bbd2d&id=ce5ac4f4ff

# formspree (contact form)
    #getform_endpoint:dc95154b-1436-4ac1-9c88-94b940335b19
    #getform_url: "https://getform.io/f"
    #formspree_email: isamsaid@polinema.ac.id

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin
  
  
assets:
  source_maps: true
  destination: "/assets"
  compression: false
  gzip: true
  defaults:
    integrity:
      {css,img,js}: false
  caching:
    enabled: true
    path: ".jekyll-cache/assets"
    type: file
  # --
  # Assets you wish to always have compiled.
  #   This can also be combined with raw_precompile which
  #   copies assets without running through the pipeline
  #   making them ultra fast.
  # --
  precompile: []
  raw_precompile: [
    #
  ]
  # --
  # baseurl: whether or not to append site.baseurl
  # destination: the folder you store them in on the CDN.
  # url: the CDN url (fqdn, or w/ identifier).
  # --
  cdn:
    baseurl: false
    destination: false
    url: null
  # --
  # See lib/jekyll/assets/config.rb
  #   for a list of defaults
  # --
  sources:
    - _assets/custom
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}

## Jekyll Admin Config
#jekyll_admin:
#  # hidden_links:
#  #   - posts
#  #   - pages
#  #   - staticfiles
#  #   - datafiles
#  #   - configuration
#  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
